ForomePlatform/Anfisa-React-Client

src/pages/ws/ui/table.tsx

https://quantori.atlassian.net/browse/FOROME-92

fix variant fetch

---

src/core/enum/func-step-types-enum.ts
src/core/enum/inheritance-mode-enum.ts
src/i18n/locales/en.ts
src/pages/filter/page.tsx
src/pages/filter/ui/query-builder/query-builder-groups.tsx
src/pages/filter/ui/query-builder/ui/modal-edit-custom-inheritance-mode-func.tsx
src/pages/filter/ui/query-builder/ui/modal-edit-filters.tsx
src/pages/filter/ui/query-builder/ui/modal-edit-inheritance-mode-func.tsx
src/pages/filter/ui/query-builder/ui/modal-operation.tsx
src/pages/filter/ui/query-builder/ui/next-step-content-item.tsx
src/pages/filter/ui/query-builder/ui/next-step-content.tsx
src/store/dtree.ts
src/ui/input-number.tsx
src/ui/select.tsx
src/utils/getFuncParams.ts
src/utils/getSortedArray.ts

In addition:
1. Fix problem with joining steps with func instructions
2. Add comments to dtree store blocks
3. Small components refactoring

Created modals to edit inheritance/custom-inheritance func steps

---

src/components/variant/drawer.tsx
src/components/variant/ui/body.tsx
src/components/variant/ui/header.tsx
src/store/variant.ts

Final version of drawer fix. Everything looks good and works well

Fixed drawer layout

---

src/i18n/locales/en.ts
src/pages/filter/page.tsx
src/pages/filter/ui/filter-control-refiner.tsx
src/pages/filter/ui/filter-control.tsx
src/pages/filter/ui/filter-refiner.tsx
src/pages/filter/ui/query-selected.tsx
src/store/filterPreset.ts
src/utils/deferRender.tsx

In addition: fix problem with loading / applying preset on filter page (filter refiner)

fix(FOROME-224): opening xl-dataset on main table

---

src/i18n/locales/en.ts
src/pages/filter/page.tsx
src/pages/filter/ui/query-builder/query-builder-total-numbers.tsx
src/store/dataset.ts
src/store/dirinfo.ts

In addition:
1. Fix problem with updating data on decision tree if we change dataset we want to work with

fix(FOROME-249): displaying exclude / include variants data

---

src/pages/ws/ui/table.tsx

If we choose different variants in main-table and then apply some filter preset + zone filter, console shows an error linked with getting data with undefined index

fix(FOROME-0): main table data error

---

src/pages/filter/ui/dtree-modal.tsx
src/pages/filter/ui/filter-control-query-builder.tsx
src/store/dtree.ts

Simplify the order of loading decision tree. Now we only need to click on desired decision tree in dropdown select.

fix(FOROME-303): load decision tree function

---

src/components/header.tsx
src/components/variant/ui/drawer-tags.tsx
src/pages/filter/page.tsx
src/store/dataset.ts
src/store/dtree.ts

After some recent filter page updating we got excess requests which is used on main table. This PR removes them.

fix(FOROME-322): remove excess requests on filter page

---

index.d.ts
src/components/variant/drawer.tsx
src/pages/filter/ui/filter-refiner-group-item.tsx
src/pages/ws/ui/column-name-item.tsx
src/pages/ws/ui/columns-list.tsx
src/pages/ws/ui/settings-panel.tsx
src/pages/ws/ui/table.tsx
src/store/wsColumns.ts

Changed the behaviour of customizing table (dnd, hide/unhide columns, reset states)

fix(FOROME-317): customize table button func

---

src/components/export-panel.tsx
src/i18n/locales/en.ts

Prohibit to export dataset if there are more than 300 variants

fix(FOROME-379): problem with export

---

src/i18n/locales/en.ts
src/pages/filter/ui/filter-control-refiner.tsx
src/pages/filter/ui/query-builder/ui/modal-save-dataset.tsx
src/pages/filter/ui/range-panel.tsx

In addition made a little range panels buttons layout fix

feat(FOROME-268): add validation for preset name

---

src/components/variant/drawer.tsx
src/components/variant/ui/body.tsx
src/pages/filter/ui/TableModal.tsx
src/store/variant.ts

It was an error which happened when we try expand all drawer content in particular dataset (e.g. Pharm_test_1)

fix(FOROME-399): drawer error

---

src/pages/filter/ui/filter-control.tsx
src/pages/filter/ui/filter-refiner.tsx
src/pages/filter/ui/query-builder/query-builder.tsx

Removed annoying scroll from right side when page content is empty

fix(FOROME-0): filter page height

---

package.json
src/i18n/locales/en.ts
src/pages/error/error.tsx
src/pages/filter/page.tsx
src/pages/main/page.tsx
src/pages/ws/page.tsx
src/router/router.tsx
yarn.lock

If we get any error on pages we will see this

feat(FOROME-425): add error boundary

---

src/core/enum/inheritance-mode-enum.ts
src/pages/filter/ui/compound-request.tsx
src/pages/filter/ui/custom-inheritance-mode.tsx
src/pages/filter/ui/query-builder/ui/custom-inheritance-mode-content.tsx
src/pages/filter/ui/query-builder/ui/modal-edit-compound-request.tsx
src/pages/filter/ui/query-builder/ui/modal-edit-custom-inheritance-mode.tsx
src/pages/filter/ui/query-builder/ui/modal-select-compound-request.tsx
src/pages/filter/ui/query-builder/ui/modal-select-custom-inheritance-mode.tsx
src/utils/getResetRequestData.ts
src/utils/getResetType.ts

Every reset select on func attrs in filter page now is able to show users choice.

fix(FOFOME-380): make select values visible

---

src/pages/filter/page.tsx
src/pages/filter/ui/enum-panel.tsx
src/pages/filter/ui/filter-control-refiner.tsx
src/pages/filter/ui/filter-control.tsx
src/pages/filter/ui/filter-refiner.tsx
src/pages/filter/ui/query-builder/ui/modal-save-dataset.tsx
src/pages/filter/ui/query-results.tsx
src/pages/filter/ui/query-selected.tsx
src/pages/main/page.tsx
src/pages/ws/page.tsx
src/pages/ws/ui/control-panel-edit-filter.tsx
src/pages/ws/ui/control-panel-preset.tsx
src/store/dataset.ts
src/store/filter.ts
src/store/filterPreset.ts
src/store/operations.ts

Every transition like refiner => main-table / main-table => refiner must save presets / conditions / zone filters from previous route

fix(FOROME-422): fix transitions between refiner and main table

---

src/components/popper-table-modal.tsx
src/components/variant/ui/drawer-note.tsx
src/components/variant/ui/drawer-tags.tsx
src/pages/filter/ui/compound-request.tsx
src/pages/filter/ui/query-builder/ui/edit-modal-buttons.tsx
src/pages/filter/ui/query-builder/ui/inheritance-mode-content.tsx
src/pages/filter/ui/query-builder/ui/modal-edit-compound-request.tsx
src/pages/filter/ui/query-builder/ui/modal-save-dataset.tsx
src/pages/filter/ui/query-builder/ui/modal-select-compound-request.tsx
src/pages/filter/ui/query-builder/ui/select-modal-buttons.tsx
src/ui/button.tsx

After recent tailwind update some buttons lost their text color inside

fix(FOROME-0): buttons text color

---

src/components/popper-table-modal.tsx

https://quantori.atlassian.net/browse/FOROME-389

fix (FOROME-389): Fix for the variant counter issue

---

src/pages/filter/ui/compound-het.tsx
src/pages/filter/ui/compound-request.tsx
src/pages/filter/ui/custom-inheritance-mode.tsx
src/pages/filter/ui/filter-refiner.tsx
src/pages/filter/ui/function-panel.tsx
src/pages/filter/ui/gene-region.tsx
src/pages/filter/ui/inheritance-mode.tsx
src/pages/filter/ui/range-panel.tsx
src/store/filter.ts

https://quantori.atlassian.net/browse/FOROME-470

feat (FOROME-470): Implemented an ability to switch between filters having the values memorized

---

src/pages/ws/ui/control-panel.tsx

https://quantori.atlassian.net/browse/FOROME-478

fix (FOROME-478): Added toaster when table is empty

---

src/pages/filter/ui/filter-refiner-groups.tsx

refactor: remove warning

---

src/pages/filter/ui/filter-refiner-groups.tsx
src/pages/filter/ui/function-panel.tsx
src/pages/filter/ui/range-panel.tsx

Just added fetchWsList() to every operation with adding attrs on refiner page

fix(FOROME-00): adding attrs on refiner page

---

src/pages/filter/ui/query-builder/ui/select-modal-buttons.tsx
src/ui/button.tsx

1. Fixed margin in select-modal-buttons
2. Fixed rounded property in Buttons component

fix(FOROME-501): select-modal-buttons margin

---

index.d.ts
package.json
src/components/variant/drawer.tsx
src/components/variant/ui/body.tsx
src/store/variant.ts
yarn.lock

Changing the order of drawer blocks is being saved after opening.

fix(FOROME-358): drawer blocks layout

---

src/pages/filter/ui/enum-panel.tsx
src/pages/filter/ui/filter-refiner-groups.tsx
src/pages/filter/ui/function-panel.tsx
src/pages/filter/ui/query-results.tsx
src/pages/filter/ui/range-panel.tsx
src/pages/refiner/page.tsx
src/store/dataset.ts

1. Removed calling ws_list from refiner with xl_dataset
2. Additionally, added loader to the left refiner's column if we load data for the first time

fix(FOROME-544): remove ws_list method from refiner with xl_datasets

---

package.json
src/index.css
stylelint.config.js

I've replaced husky hooks with simple-git-hooks due to windows odd bugs

feat(FOROME-349): replace hooks with simple-hooks

---

index.d.ts
src/pages/filter/ui/query-selected.tsx
src/pages/ws/page.tsx
src/store/dataset.ts

1. Main-table requests optimization
2. Transition between refiner-ws pages optimization
3. Fixed getting the incorrect amount of variants on refiner, ws pages

bug(FOROME-550): incorrect amount of variants
